### ISSUE TITLE
Valid e-mail addresses rejected

### ISSUE THREAD

**Issue by m4p-adm** [onetimesecret/onetimesecret#104]
When trying to sign up with a valid email address in the format of abc+def@ghi.com the login form complains that the address format is invalid.

Actually though these addresses are valid and widely used by advanced users, see https://www.cs.rutgers.edu/~watrous/plus-signs-in-email-addresses.html

**Comment by jaycburton** [comment]
Did you ever find any resolution or workaround for this? I frequently use a Gmail email address in this manner so I do not have to otherwise create a bunch of unique individual email addresses.

**Comment by thunfischbrot** [comment]
Unfortunately I gave up.

**Comment by jaycburton** [comment]
Wow, I am sorry to hear that there was no resolution to what I think could be a relatively common situation. Maybe the dev has given up on improving the code? I will update here if I find out anything, unless I just give up as well. :)

**Comment by thunfischbrot** [comment]
I assume from a cursory look that the issue lies in the regex at https://github.com/onetimesecret/onetimesecret/blob/8ba0511e74b64280003691251dd99b04915d42ea/public/web/libs/onetime-api.php#L21
Did not look into it further though.

**Comment by thunfischbrot** [comment]
Ok, the regex could probably be replaced with the one from http://emailregex.com/

**Comment by YLearn73249** [comment]
Still not resolved as the issue is still present. I always find this frustrating and tend to avoid services that do this, so I won't be signing up with this one until/if they fix it. I do wish they would fix this though.

The plus sign ("+") is one of a number of valid special characters that can be used in email addresses as defined by the RFCs and I have often found that either the programmer who wrote it was simply unaware of this when writing their code or they are trying to take an "easy" way out of sanitizing user input to prevent security issues.
