### ISSUE TITLE
onetimesecret.com in maintainance mode?

### ISSUE THREAD

**Issue by timvlaer** [onetimesecret/onetimesecret#113]
Just checking, the onetimesecret.com website is in 'maintenance' mode for more than 24 hours. Are you aware of this and is there any plan to bring it back online?

**Comment by bryanpost** [comment]
No updates on their page, socials, or here. Makes me kind of nervous about using the service! I have no idea what the severity of the issue is.

**Comment by efimk-lu** [comment]
Maybe it's a good place to ask, any recommended alternatives?

**Comment by LuciousLisa** [comment]
Three days and counting. I pinged them on Twitter, asking if they're okay. Servers are located in Germany, but I still second the nervousness about using it, until we get some assurances.

**Comment by jaszczur171** [comment]
This is getting me seriously nervous now. This is a recommended service within my company to distribute credentials to 3rd party organisations.

**Comment by tostringtheory** [comment]
@jaszczur171 / @efimk-lu - Our company also uses this to send passwords when needed.  Sadly, there doesn't appear to be any help on social media, however one of their last posts (from last year) on Facebook was mentioning a OneTimeSecret clone - https://cloak.sh .  The code was forked from OTS and you can see the obvious similarities.

**Pros** : works essentially exactly the same as OTS.
**Cons** : While this was forked from OneTimeSecret - to https://github.com/openbridge/ob_cloak , I'm not 100% sure that the source is matching what is deployed on this one.

This is probably what we'll be using for now.  Although I'm highly considering writing my own version in C# now.

**Comment by lud0veek** [comment]
Guy's don't send username & password in the same secret. It will avoid stress in case of security breach.

Regarding the issue, no news through social media is really strange... Hope this amazing service will come back soon!

**Comment by onetimesecret** [comment]
Sorry for the inconvenience folks. There was a maintenance outage at linode
that they had given us a heads up about but there was a permissions issue
that prevented the site from coming back up. It was a minor intervention
but I wasn't able to get to it until today.

**Comment by jaszczur171** [comment]
@onetimesecret I know you provide the service for free and there should be no expectations from user side at all, but giving no details to your users for 4 days is unacceptable. We are talking about a piece of software centred around security and THAT requires trust. That trust has now been put into question.

@tostringtheory I hate reinvent the wheel, but the situation being what it is here might not be any other choice.

**Comment by oleschri** [comment]
@onetimesecret 
Suggestion: give at least a daily update via your twitter account.

**Comment by LuciousLisa** [comment]
> Sorry for the inconvenience folks. There was a maintenance outage at linode that they had given us a heads up about but there was a permissions issue that prevented the site from coming back up. It was a minor intervention but I wasn't able to get to it until today.

Hey, thanks for letting us know, glad you're back!  
Considering the trust issues this caused, maybe you could consider finding some way to set up a 'canary in the coal mine' type way of letting folks know your service hasn't been compromised? Just a thought.

**Comment by onetimesecret** [comment]
Thanks for the candid feedback. I understand the concerns. A few comments:

With regards to responding sooner, that would be my preference as well.
This issue tracker is for the opensource project and not the site itself so
I don't check responses here on a daily basis which you can see from the
other open code related tickets (and have notification disabled). It's a
similar story with Twitter and Facebook which you can see are not regularly
used. In terms of responding here, I saw this after getting the site back
up so I wasn't aware that I was leaving anyone hanging (there were no
direct emails or phone calls this time).

We have a pretty good track record in terms of uptime and availability over
the 8 or 9 years we've been around. The site runs itself with outages being
few and far between. Not being available sucks though, especially for
several days and it's also disruptive for folks that rely on it day-to-day.

In terms of trust, there are a few additional things to consider:

- We don't support end-to-end encryption as a feature so we intentionally
are not the most secure option for sharing the most sensitive information
or conversations. This is mainly based on in non-obvious insecurity around
relying on javascript for that. (see [this hacker news thread](
https://news.ycombinator.com/item?id=7903720) in particular the comments
from Thomas Ptacek).
- When a secret includes a passphrase, that passphrase is used when
encrypting the content. Not supporting end-to-end encryption means that
this happens server-side but that passphrase is not stored so this does
provide further security for the data at rest.
- When a secret is received, the content is deleted from our server prior
to being sent back in the request and we have no way of sending that
content again if there were any issues with receiving it. This is by design
to ensure that the content is available one time only but it also means the
content can be lost in transit. So there are better tools for sharing
content that cannot be recovered or regenerated on the sender's end.
- In terms of trust around intervention by third-parties, we have not at
any time sent secret content to anyone other than the person or system
accessing a secret by it's URL. We don't have a canary but we do have other
approaches in place if we are ever in that situation. And we would only do
that when it was legally binding.


On the idea of running other services or starting other projects, I happily
support any and all ideas along those lines. Anything we can do to improve
how we handle sensitive information is a net-win. A lot of people runs
their own services based on the opensource project for example. The initial
idea behind the site was to be better than the default alternative of
copying and pasting passwords into emails and DMs -- particularly when it
comes to less technically savvy people who often aren't aware of any of
these concerns. I like ti think we've done a decent job of that over the
years. Outages suck and this one was regrettable but I hope this at least
gives some context from our perspective.

**Comment by yhorndt** [comment]
Thanks for being back up and thanks for the explanation!

When I realized that the service wasn't working, we work via the api, I just put in a message that would come up if it was still not responding.. There are a lot of alternatives, it is even possible to host the service on your own server, so I don't know what the frustration is about.

**Comment by robmaas** [comment]
@onetimesecret The site has been in maintenance mode again for quite a while. Any update?

**Comment by onetimesecret** [comment]
It was another planned maintenance on the host machine at Linode. Apologies
for the delay but it's back now.
