### ISSUE TITLE
Phising on Google Ads

### ISSUE THREAD

**Issue by luklapp** [onetimesecret/onetimesecret#149]
There is a google ad from www.onet**ï**mesecret.com, which is definitely not the original! 

![image](https://user-images.githubusercontent.com/6569846/104628493-9503bd00-5698-11eb-998f-afff40887d28.png)

I already reported it to Google (https://safebrowsing.google.com/safebrowsing/report_phish). Can we do anything else?

**Comment by jamiecounsell** [comment]
Also came across this today. The attacker actually grabs the info client-side and sends it to a third party domain before you even submit the form:

![Screen Shot 2021-01-18 at 4 45 18 PM](https://user-images.githubusercontent.com/2321599/105051027-5ecd9100-5a3c-11eb-989e-394c01616167.png)

Unfortunately this is the dark side of open sourcing full applications like this.

**Comment by rugk** [comment]
I wonder what makes people do this…

What gain do they have to grab that data there? Just stupid…

**Comment by rugk** [comment]
So https://onetimesecret.com/ is legit?

**Comment by delano** [comment]
> So https://onetimesecret.com/ is legit?

Yeah that's the correct URL for the site that I've been running since 2011.

--

@luklapp @jamiecounsell I came across those ads a few months ago and reported them to google as a phishing attack. I assumed they were doing shady server-side so there was no obvious sign that it was any different. Thanks for setting me straight on that.

I'm pretty sure it was them that flagged the original site with OpenDNS a few months ago. Users were getting the big, scary red warning for half a day. I'll look into this again to see what else I can do. In the meantime, I've been posting a warning at the top of the page. 

<img width="929" alt="Screen Shot 2021-03-10 at 8 07 06 AM" src="https://user-images.githubusercontent.com/1206/110659652-9ec90e80-8177-11eb-8476-879e95e68157.png">

**Comment by thoernle** [comment]
> Also came across this today. The malicious agent actually grabs the info client-side and sends it to a third party domain before you even submit the form:
> 
> ![Screen Shot 2021-01-18 at 4 45 18 PM](https://user-images.githubusercontent.com/2321599/105051027-5ecd9100-5a3c-11eb-989e-394c01616167.png)
> 
> Unfortunately this is the dark side of open sourcing full applications like this.

Thats not really a problem of open sourcing these applications. Other platforms with closed source like privnote.com have this problem quite frequently.

**Comment by fmendezp** [comment]
Another one here: https://orretimesecret.com/

**Comment by rugk** [comment]
@fmendezp the for telling but please don't link it publicly. At the very little, break the link by using the "hxxps://" protocol or so. Do not spell the whole domain, so people do not visit it and it is not further spread.

You can send the URL to the domain owner though via mail and/or directly report it as a phishing page via channels here: https://decentsecurity.com/#/malware-web-and-phishing-investigation/

Please note to make sure its actually malicious though! After all this is a software that one can self host and such new instances of such a page alone are legitimate, as long as they don't try to spoof another page or somehow grab content/have bad code changes/additions in them to do malicious things.

**Comment by delano** [comment]
Thanks everyone for the all input on this. I'll close this ticket now but by all means create another if it comes up again.
