### ISSUE TITLE
Javascript-based end-to-end-encryption?

### ISSUE THREAD

**Issue by blobgo** [onetimesecret/onetimesecret#17]
Why don't use Javascript encryption to encrypt the text before it is sent to the sever? This way you would have real end-to-end-encryption.
An example service which does this already is img.bi ([website] (https://img.bi/), [source] (https://github.com/imgbi/img.bi)).

So it is not impossible and it may improve the security of the service.

**Comment by stephenpaulger** [comment]
Worth considering... http://tonyarcieri.com/whats-wrong-with-webcrypto

**Comment by delano** [comment]
Thanks for the link @stephenpaulger. Provides interesting background. 

The issue generally is that in-browser encryption introduces a large vector of insecurity. It's true that it has the potential to provide greater security for individual messages. The issue is that the browser is an inherently insecure environment and in addition varies so widely from device to device. The goal of One Time Secret is to be secure enough for most situations while also maintain a reasonable level of convenience for less technical users. In a nutshell, in-browser encryption _could_ help in the most significant cases but could also just as easily compromise it. 

So, we sacrifice potentially better message security rather than give a false impression of security.
