### ISSUE TITLE
installation KO on a fresh debian

### ISSUE THREAD

**Issue by isAAAc** [onetimesecret/onetimesecret#172]
@delano : hi guy ;)

one week i try hard to install onetimesecret on a fresh debian without any success, 
could the Readme.md been upgraded with fresh and working commands please ?

**Comment by delano** [comment]
Hey @isAAAc, it is a pain now to install and I've been working slowly on a 0.11 release for a while. It will have a bunch of that clean up and just all around better in general for getting started.

I don't know the date yet, but working on it!

**Comment by isAAAc** [comment]
ok , 
thx for your quick answer and for your work, 
we were using onetimesecret in my last job, that's why i would install it in the new one ^^, 
is there a work in progress to help you  ? i'm a (real) noob on ruby, but i can "beta testing" a deploy on debian if needed, 
just tell me ;)

**Comment by isAAAc** [comment]
@delano : i suggest to use `rbenv`  , what do you think about ?

**Comment by delano** [comment]
That's great to hear. 

I will push up a new branch in the next few weeks and that will be a work in progress. As for rbenv, I like it myself. I don't always use virtual environments but when I do I use rbenv.

Be sure to read the documentation for the `rbenv rehash` command.

**Comment by delano** [comment]
Quick update: you can preview the next release by its tag now.

[v0.11.0-RC1](https://github.com/onetimesecret/onetimesecret/releases/tag/v0.11.0-RC1)

_N.B. It's a tag on WIP code so you'll see weirdness if you try to run. I pushed the tag so I can reference the upcoming changes._

**Comment by CBB3810** [comment]
Hi All, Here's a way to get it installed specifically on Ubuntu 20.04 with it's native OPENSSL 1.1.1
 In Ubuntu Version 20.04 because it natively runs OpenSSL Version 1.1.1, install the following packages.
 
  sudo apt install build-essential libyaml-dev libevent-dev zlib1g zlib1g-dev openssl libssl-dev libxml2 libtinfo-dev libreadline-gplv2-dev gnupg2 software-properties-common redis -y
 
  From: https://github.com/rvm/ubuntu_rvm  
 
  #Open a terminal (Ctrl+Alt+T) and run:
 
  sudo apt-add-repository -y ppa:rael-gc/rvm
 
  sudo apt update && sudo apt install rvm -y
 
  #Add your user to rvm group ($USER will automatically insert your username):  
  sudo usermod -a -G rvm $USER
  #With each user that will use ruby, login to their user and run this command I did it to root, cboley and ots once I created them:
  ===================================================================================================================================
  echo 'source "/etc/profile.d/rvm.sh"' >> ~/.bashrc
  #With each user that will use ruby, login to their user and run this command I did it to root, cboley and ots once I created them:
 
  #reboot:  sudo reboot now [this is done to make sure all the env changes are picked up by the respective users I'm not sure it's necessary]
 
  #Now install Ruby 2.6.0
  sudo -i
 
  rvm install 2.6.0
 
  #Now update the (ruby) gem system
  gem update --system

  sudo groupadd ots
  useradd -b /home -m -g ots -p $(echo "E)-GfRu8fsqvSDc5:zRXc!5" | openssl passwd -1 -stdin) -c "ONETIMESECRET - SrvrAcct" -s /bin/bash ots
  sudo usermod -a -G rvm ots
  sudo mkdir /etc/onetime /var/log/onetime /var/run/onetime /var/lib/onetime
  sudo chown ots /etc/onetime /var/log/onetime /var/run/onetime /var/lib/onetime
  sudo su - ots
  echo 'source "/etc/profile.d/rvm.sh"' >> ~/.bashrc
  exit
 
  reboot: sudo reboot now [this is done to make sure all the env changes are picked up by the respective users I'm not sure it's necessary]
  #Log back in.
 
  sudo su - ots
 
  git clone https://github.com/onetimesecret/onetimesecret.git
 
  cd onetimesecret
 
  gem list bundler  #[ This will enumerate the default bundler in the output. at the time of this writing it was 2.4.5 ]
 
  nano Gemfile  # look for the following line [ gem 'bundler', '2.3.17', ] delete the trailing [ , ]  from the line and change version.
  # it should look like this when done: [ gem 'bundler', '2.4.5' ] Then save the file.
 
  cp Gemfile Gemfile.lock
 
  bundle lock --add-platform x86_64-linux
 
  bundle config set --local frozen 'true'
 
  bundle install
 
  # If you see this at the bottom of your output then you've done it correctly:
  # Installing thin 1.8.1 with native extensions
  #Bundle complete! 19 Gemfile dependencies, 32 gems now installed.
  #Use `bundle info [gemname]` to see where a bundled gem is installed.
  #Post-install message from httparty:
  #When you HTTParty, you must party hard!

  bin/ots init
 
  #You can safely ignore those warnings. The output will look like:
=============================================================================================================
/home/ots/onetimesecret/lib/onetime/core_ext.rb:30: warning: constant ::Fixnum is deprecated
/usr/share/rvm/gems/ruby-2.6.0/gems/attic-0.5.3/lib/attic.rb:13: warning: constant ::Fixnum is deprecated
/usr/share/rvm/gems/ruby-2.6.0/gems/gibbler-0.8.9/lib/gibbler.rb:654: warning: constant ::Fixnum is deprecated
/usr/share/rvm/gems/ruby-2.6.0/gems/gibbler-0.8.9/lib/gibbler.rb:655: warning: constant ::Bignum is deprecated
===============================================================================================================
cp -rp etc/* /etc/onetime/

chown -R ots /etc/onetime /var/lib/onetime

chmod -R o-rwx /etc/onetime /var/lib/onetime

**********Update the configuration************
nano /etc/onetime/config
-- Update your secret key  
# Generating a global secret:  
dd if=/dev/urandom bs=20 count=1 | openssl sha256
1+0 records in
1+0 records out
20 bytes copied, 0.000202585 s, 98.7 kB/s
(stdin)= 38d8693165f490093a40dacea9f4e24674b498d6cab5fe145b9e7015e710540f   <=== ***This is your key string***
*Store it in your password manager because it's included in the secret encryption

-- Add or remove locales
-- Update the SMTP or SendGrid credentials
   * Update the from address -- it is used for all sent emails
-- Update the the limits at the bottom of the file
  *These numbers refer to the number of times each action can occur for unauthenticated users.
  *If you would like to increase the limits for authenticated users too:
  *see (lib/onetime.rb](https://github.com/onetimesecret/onetimesecret/blob/main/lib/onetime.rb#L261-L279)
 
-- nano /etc/onetime/redis.conf
   * The host, port, and password need to match
   
-- nano /etc/onetime/locale/*
   * Optionally you can customize the text used throughout the site and emails
   * You can also edit the :broadcast string to display a brief message at the top of every page

To run on a server: /home/ots/onetimesecret/bundle exec thin -d -S /var/run/thin/thin.sock -l /var/log/thin/thin.log -P /var/run/thin/thin.pid -e prod -s 2 restart

**Comment by CBB3810** [comment]
I just dev'd all of the above out today. I'm still trying to configure the proper pieces of the config files. I know I'm 95% there and just need to figure out the options in the cfg files. I figure I'd share. If there's any good examples of config files.. I'm all ears.

**Comment by CBB3810** [comment]
I'm waayyy out of my depth here I don't know enough about these messages to understand, any pointers would be helpful:

ots@otsdev01:~/onetimesecret$ bundle exec thin -e dev -R config.ru -p 8091 start

/home/ots/onetimesecret/lib/onetime/core_ext.rb:30: warning: constant ::Fixnum is deprecated
/usr/share/rvm/gems/ruby-2.6.0/gems/attic-0.5.3/lib/attic.rb:13: warning: constant ::Fixnum is deprecated
/usr/share/rvm/gems/ruby-2.6.0/gems/gibbler-0.8.9/lib/gibbler.rb:654: warning: constant ::Fixnum is deprecated
/usr/share/rvm/gems/ruby-2.6.0/gems/gibbler-0.8.9/lib/gibbler.rb:655: warning: constant ::Bignum is deprecated
Traceback (most recent call last):
        20: from /usr/share/rvm/gems/ruby-2.6.0/bin/ruby_executable_hooks:24:in `<main>'
        19: from /usr/share/rvm/gems/ruby-2.6.0/bin/ruby_executable_hooks:24:in `eval'
        18: from /usr/share/rvm/gems/ruby-2.6.0/bin/thin:25:in `<main>'
        17: from /usr/share/rvm/gems/ruby-2.6.0/bin/thin:25:in `load'
        16: from /usr/share/rvm/gems/ruby-2.6.0/gems/thin-1.8.1/bin/thin:6:in `<top (required)>'
        15: from /usr/share/rvm/gems/ruby-2.6.0/gems/thin-1.8.1/lib/thin/runner.rb:159:in `run!'
        14: from /usr/share/rvm/gems/ruby-2.6.0/gems/thin-1.8.1/lib/thin/runner.rb:203:in `run_command'
        13: from /usr/share/rvm/gems/ruby-2.6.0/gems/thin-1.8.1/lib/thin/controllers/controller.rb:72:in `start'
        12: from /usr/share/rvm/gems/ruby-2.6.0/gems/thin-1.8.1/lib/thin/controllers/controller.rb:182:in `load_rackup_config'
        11: from /usr/share/rvm/gems/ruby-2.6.0/gems/thin-1.8.1/lib/rack/adapter/loader.rb:33:in `load'
        10: from /usr/share/rvm/gems/ruby-2.6.0/gems/thin-1.8.1/lib/rack/adapter/loader.rb:33:in `eval'
         9: from config.ru:1:in `<main>'
         8: from config.ru:1:in `new'
         7: from /usr/share/rvm/gems/ruby-2.6.0/gems/rack-2.1.4.1/lib/rack/builder.rb:71:in `initialize'
         6: from /usr/share/rvm/gems/ruby-2.6.0/gems/rack-2.1.4.1/lib/rack/builder.rb:71:in `instance_eval'
         5: from config.ru:30:in `block in <main>'
         4: from /home/ots/onetimesecret/lib/onetime.rb:53:in `load!'
         3: from /home/ots/onetimesecret/lib/onetime/email.rb:22:in `setup'
         2: from /usr/share/rvm/gems/ruby-2.6.0/gems/mail-2.5.5/lib/mail/mail.rb:106:in `defaults'
         1: from /usr/share/rvm/gems/ruby-2.6.0/gems/mail-2.5.5/lib/mail/mail.rb:106:in `instance_eval'
/home/ots/onetimesecret/lib/onetime/email.rb:25:in `block in setup': undefined method `[]' for nil:NilClass (NoMethodError)
