### ISSUE TITLE
Language selection

### ISSUE THREAD

**Issue by WvanDam** [onetimesecret/onetimesecret#177]
It's great that you make your website available in multiple languages. It's less great that I appear to be stuck with a language I can't read. Please offer a language selection option, so I can go back to English. Thnx!

**Comment by onetimesecret** [comment]
Yeah sorry about that. I pushed an update that included a few new
languages. It also included my brainwave of a change that sorted the
language list alphabetically. The first element is also implicitly used as
the default language (arabic in this case). Were you using Safari by any
chance?

I pushed the quick fix to correct the config. I'll include a fix for that
root cause in 0.11 (added a key that sets the default explicitly). If it's
still happening as of this comment, please let me know bc it means there's
something else to fix.

**Comment by WvanDam** [comment]
Thanks for the quick solution. It's looking good now. And I was indeed using Safari.
