### ISSUE TITLE
Problem installing fresh install of CentOS 7

### ISSUE THREAD

**Issue by spectranets** [onetimesecret/onetimesecret#212]
Hello. I have tried several times to install OTS on a fresh CentOS 7 box without success. I manage to get past one error and run into another, does anyone have clear instructions or can provide assistance with installing on a CentOS 7 OS?

**Comment by rshosting** [comment]
I managed to install on fresh Centos 7 after playing with a few versions of ruby and bundler. I am even able to execute the last "thin" web server command without error.
However, I am stuck at website graphical user interface as links to create password or secret link are not working. Most likely due to /etc/onetime/config which I am facing difficulty to understand.
