### ISSUE TITLE
You can copy and paste, or take a screenshot to save a secret forever

### ISSUE THREAD

**Issue by bufala8** [onetimesecret/onetimesecret#23]
This kind of defeats the purpose no?  Am I missing something?

**Comment by stephenpaulger** [comment]
You could also remember it or shout it our your window and that's your business.

onetimesecret it useful for sharing a secret with one person and allowing that person to know that no-one has received it before them and that the secret won't be available to anyone that happens to find the link in an archived email or chat transcript at some point in the future. If the intended recipient shares the secret after receiving it, they are responsible for that.

**Comment by delano** [comment]
Further to what @stephenpaulger pointed out, copying and pasting text and even taking screenshots is not definitive proof of what was written or who wrote, unlike an image, video or any other kind of media file which often contains metadata that can identify or help to identify the source. Not to mention that multimedia files contain several orders of magnitude more data which can be also be used to identify the source through various forms of analysis (e.g. voice detection). This is the reason why One-Time Secret is and always will be text-only: to avoid any and all non-obvious forms of intrusion. 

I'm going to close the issue since it's non-actionable but this is a very good question so thanks for bringing it up. Feel free to post follow-up questions.
