### ISSUE TITLE
Images and icons not showing

### ISSUE THREAD

**Issue by vgallegoiz** [onetimesecret/onetimesecret#261]
I have configured onetimesecret with Docker and I can't see any image or icon from the site. 

![image](https://github.com/onetimesecret/onetimesecret/assets/55552575/ce4c3567-6382-4c17-ad21-d85400b17c4c)

**Comment by Vasilevs2** [comment]
@vgallegoiz I found the solution. The problem is in the docker-compose.yml file, namely in the Volume block. When you create a container, the files inside are replaced with files from the local project folder and get 1000:1000 permissions instead of root:root. You can remove this block from the docker-compose.yml file. In this case, the files will be loaded into the image only when building the docker and all images will be displayed

Try it!

**Comment by vgallegoiz** [comment]
Thanks!

**Comment by vgallegoiz** [comment]
Thanks!
