### ISSUE TITLE
Migration to organization

### ISSUE THREAD

**Issue by Neustradamus** [onetimesecret/onetimesecret#269]
Dear @onetimesecret team, @delano,

It is possible to migrate this personal account to organization?

Converting:
- https://help.github.com/articles/converting-a-user-into-an-organization/

Thanks in advance.

**Comment by Neustradamus** [comment]
@delano, @venkatamutyala: Can you look this ticket?

**Comment by delano** [comment]
@Neustradamus, can I ask why? We use a different account for our organization so we haven't had a need to migrate this one.

**Comment by Neustradamus** [comment]
@delano: Thanks for your answer after several months!

Currently @onetimesecret is a personal account but it is not a person... It is for this, it is needed to change it.

A lot of projects have already done it without any problems...

**Comment by delano** [comment]
After thinking about it more I found that [renaming the user account and manually transferring the repo to a new org called onetimesecret](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-your-personal-account/converting-a-user-into-an-organization#keep-your-personal-account-and-create-a-new-organization-manually) was a workable solution. It maintained the continuity of the commits, comments etc of the user account and allowed me to continue using the account to "Login with Github" for 3rd party services. 

I actually went ahead with the change but the attempt was thwarted. Due to the amount of activity on this repo (mainly the number of clones/forks) it's not possible to transfer "onetimesecret" the repo to "onetimesecret" the new github org. 

![Transfer repository](https://github.com/onetimesecret/onetimesecret/assets/1261652/354b9375-5d2e-43ea-be4f-a6ca4f2221d7)


I just renamed the org and then the username back. That still leaves the option of directly converting the account as a possibility. Since there's no practical benefit to making the change I'm going to hold off on that and leave things as-is. 

However, I will say that I agree that having it as an org and org repo ultimately makes the most sense. It's just unfortunate that it's a bit of a prickly process.

**Comment by Neustradamus** [comment]
@delano: Examples here of success:
- https://github.com/nerzhul/ocsms -> https://github.com/nextcloud/ocsms
- https://github.com/tigaseinc/tigase-server -> https://github.com/tigase/tigase-server
- https://github.com/boothj5/profanity -> https://github.com/profanity-im/profanity
- https://github.com/asciimoo/searx -> https://github.com/searx/searx

All old links have been redirected, Issues, PRs, Forks, etc., no lost, no error.

It is possible to convert or to migrate, I am suprised.
Can you retry?
I can help you if you want.

What 3rd party services?

Maybe you can contact GitHub here: https://support.github.com/request.

**Comment by delano** [comment]
@Neustradamus Why is this so important?

**Comment by Neustradamus** [comment]
@delano: Onetime Secret is not a person...

**Comment by delano** [comment]
@Neustradamus I disentangled the onetimesecret account and have converted it to an organization at long last. 🌻

https://github.com/onetimesecret

**Comment by Neustradamus** [comment]
@delano: Very good job, it is really better now! :)

In more, you can add social links in the organization settings...
- https://github.com/organizations/onetimesecret/settings/profile
