### ISSUE TITLE
Email not working

### ISSUE THREAD

**Issue by JBlakistone** [onetimesecret/onetimesecret#280]
Using Power Automate to generate a secret, everything says successful and I see the secrets created on my account, however the email isn't sent.  I have tried multiple emails and never received any.

**Comment by subwaytree** [comment]
Hi,
I have just experienced the same problem. I have created an official one and 3 for testing. All 4 are still on Received - None for over 30 minutes. Normally, these secrets go straight to the recipient, don't they?
Thanks

**Comment by Abasoft2024** [comment]
Still persist....

**Comment by delano** [comment]
Sorry for the super slow response. Between the tickets here and email support, I lost track of the meant to be replying to. 

We switched email providers today so here's to hoping🤞 emails are sending reliably again.

**Comment by Abasoft2024** [comment]
Hi, still persist issue:

[Interfaz de usuario gráfica, Texto, Aplicación, Correo electrónico  Descripción generada automáticamente]


Atentament,

Ricard Gascó | Technical Manager

[Abasoft]<http://www.abasoft.es/>
Juan de Sada 48, local.
08028 Barcelona
T. +34 934 902 142

www.abasoft.es<http://www.abasoft.es/>
Aquest missatge i els fitxers annexos són confidencials. Aquests contenen informació reservada de la empresa que no pot ser difosa. Si vostè ha rebut aquest correu per error, tingui l'amabilitat d'eliminar-lo del seu sistema i avisar el remitent mitjançant reenviament a la seva adreça electrònica; no haurà de copiar el missatge ni divulgar el seu contingut a cap persona.
D'acord amb el dret d'informació establert a l' article 12 del RGPD i en base a l' article 11 de la LOPDGDD, si requereix tota informació addicional sobre el tractament de les seves dades personals, se li facilitarà enviant un email a l'adreça email ***@***.******@***.***>.

De: Delano ***@***.***>
Enviado el: miércoles, 3 de abril de 2024 0:59
Para: onetimesecret/onetimesecret ***@***.***>
CC: SAT - Abasoft,S.L. ***@***.***>; Comment ***@***.***>
Asunto: Re: [onetimesecret/onetimesecret] Email not working (Issue #280)


Sorry for the super slow response. Between the tickets here and email support, I lost track of the meant to be replying to.

We switched email providers today so here's to hoping🤞 emails are sending reliably again.

**Comment by paulmellors40** [comment]
I'm getting a 404 and no email everytime I try and use that function by API

**Comment by delano** [comment]
Taking a look now

**Comment by delano** [comment]
It took a little bit to figure out exactly what was happening. This particular issue was introduced when we switched to a new email provider recently. 

The new provider refuses to send messages with a from address that isn't verified (within their system). It didn't surface during testing for the migration b/c we use @onetimesecret.com email address -- all of which are considered verified at the domain level (vs each individual address). @paulmellors40 Thanks to your comment today, I was able to find the errors in the logs right away and sorted everything else out from there. 

The fix is live and I'm merging them here now as well.
