### ISSUE TITLE
ux: "Or generate a random password" is confusing

### ISSUE THREAD

**Issue by WofWca** [onetimesecret/onetimesecret#286]
![image](https://github.com/onetimesecret/onetimesecret/assets/39462442/1455900d-d6b4-42e4-b4e8-8dffdcda1fe7)

It looks like it applies to the "passphrase" field and not the contents of the secret. Maybe putting the "generate password" button right beside the secret text would work better, in addition to just making it change the contents of the text field.

In addition it makes sense to add "generate random" for the passphrase field, though that might add confusion (like "what? two passwords??)

**Comment by delano** [comment]
Until we do a comprehensive redesign, I updated the button layout within the constraints of the current design to help make this a bit less confusing.

What do you think?

![Capture-2024-06-10-141205](https://github.com/onetimesecret/onetimesecret/assets/1206/856f0d03-09db-4050-9693-1817198037fb)

**Comment by WofWca** [comment]
I guess this is a little better, but I'd say the issue is still there.

Hopefully the new design will address this.

**Comment by delano** [comment]
Just circling back on this. We made another update so that there's only a single button bar. It's still possible to generate a password with a single click (which is a common usecase), but the main secret button takes the full width as soon as any content it entered. 

![onetime-one-button-20240902-after](https://github.com/user-attachments/assets/81285dae-7723-419a-a8c9-1b41c9ee9620)

![onetime-one-button-20240902](https://github.com/user-attachments/assets/f4177198-32dc-45ec-8c2f-bcb1d1ba5a38)
