### ISSUE TITLE
Dockerhub account? 

### ISSUE THREAD

**Issue by venkatamutyala** [onetimesecret/onetimesecret#306]
As far as I know this is a truly FOSS project. It would be nice to have an official dockerhub image that people can trust/use versus having to build it themselves. Do you already have an account like this: https://www.docker.com/community/open-source/application/ ?

**Comment by delano** [comment]
Yeah that's a great point. Thanks for raising this up.  

We have an account for onetimesecret on dockerhub but haven't been using it obviously. I'm updating the docker (and docker compose) configs concurrent with the Ruby 3 work. I haven't looked into building and pushing images via Github Actions but I imagine that's a thing. Would you be interested to help with that?

**Comment by venkatamutyala** [comment]
Absolutely! Can you let me know when your most recent commits have been pushed up?

**Comment by danselmi-intecrowd** [comment]
Since the dockerhub image is tagged linux/arm64 it doesn't work on linux/amd64. Is that easy to change or work around? Thanks!

**Comment by venkatamutyala** [comment]
It probably just needs to be built for cross-platform upon publishing to dockerhub.

**Comment by delano** [comment]
@venkatamutyala Exactly yeah. The latest code ready to build is [v0.13.0-RC3](https://github.com/onetimesecret/onetimesecret/releases/tag/latest) btw.  I pushed an [arm64 image](https://hub.docker.com/layers/onetimesecret/onetimesecret/next/images/sha256-b0cfb3996dc6c395579f221da7879642c357aadf4e5a15a03b1a4f6716990653?context=explore) for that tagged release.  

Did you want to give it a go with the github action for building these? Otherwise I'll have a look probably this weekend.

**Comment by delano** [comment]
@danselmi-intecrowd The amd64 image is available now as well. Thanks for the heads up. 

For anyone's interest, I followed the process documented in this [very relevant docker blog post](https://www.docker.com/blog/faster-multi-platform-builds-dockerfile-cross-compilation-guide/). 

```bash
  # Create a new builder instance
  $ docker buildx create --use

  # Re-build the image using `buildx` 
  $ docker buildx build --platform=linux/amd64,linux/arm64 . -t onetimesecret/onetimesecret -t onetimesecret/onetimesecret:next -t onetimesecret/onetimesecret:latest -t onetimesecret/onetimesecret:v0.13.0-RC3 --push
```
