### ISSUE TITLE
Howto use https?

### ISSUE THREAD

**Issue by PiNotEqual3** [onetimesecret/onetimesecret#49]
I got the local installation working (http://mydomain.de:7143) but I can't use https (https://mydomain:7143).

```
ots@host:~/onetimesecret$ bundle exec thin -e dev -R config.ru -p 7143 start
>> Thin web server (v1.5.0 codename Knife)
>> Maximum connections set to 1024
>> Listening on 0.0.0.0:7143, CTRL+C to stop
!! Invalid request
```

I guess I need to include the certificate somewhere?

```
:site:
  :host: mydomain.de:7143
  :domain: mydomain.de
  :ssl: true
```

Can you please give me a hint what I am doing wrong?
Without https the application does not make any sense.

**Comment by onetimesecret** [comment]
For HTTPS, you need to use a proxy like httpd or nginx.

On Jan 5, 2017 01:01, "PiNotEqual3" <notifications@github.com> wrote:

I got the local installation working (http://mydomain.de:7143) but I can't
use https (https://mydomain:7143).

ots@host:~/onetimesecret$ bundle exec thin -e dev -R config.ru -p 7143 start
>> Thin web server (v1.5.0 codename Knife)
>> Maximum connections set to 1024
>> Listening on 0.0.0.0:7143, CTRL+C to stop
!! Invalid request

I guess I need to include the certificate somewhere?

:site:
  :host: mydomain.de:7143
  :domain: mydomain.de
  :ssl: true

Can you please give me a hint what I am doing wrong?
Without https the application does not make any sense.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/onetimesecret/onetimesecret/issues/49>, or mute the
thread

**Comment by PiNotEqual3** [comment]
ok, thanks.

I am using apache and got it working by adding the proxy module:

```
sudo a2enmod proxy proxy_http
```

and setting it up in a `<VirtualHost>` with SSLEngine:

```
ProxyPass / http://mydomain.de:7143/
ProxyPassReverse / http://mydomain.de:7143/
```

**Comment by GeneralFox** [comment]
PiNotEqual3 no problem at all with css and page rendering ? 
I was unable to view the page with correct layout, i.e css / javascript.
![2017-04-14 17_30_23-share a secret - one time](https://cloud.githubusercontent.com/assets/27002780/25047618/2af42b14-2138-11e7-9110-fa68eec78638.png)

**Comment by PiNotEqual3** [comment]
@GeneralFox yes, I think I did exactly the same. There is also this question with the same problem: https://github.com/onetimesecret/onetimesecret/issues/33#issuecomment-271017901
