### ISSUE TITLE
Remove Google analytics

### ISSUE THREAD

**Issue by rugk** [onetimesecret/onetimesecret#50]
As a privacy/security-focused service you should certainly not use Google Analytics. For obvious reasons…

It is used [on all sites](https://github.com/onetimesecret/onetimesecret/search?utf8=%E2%9C%93&q=google-analytics) as far as I see.

If you really need these stats you might consider running something privacy-friendly alternative such as [piwik](https://piwik.org/).

In any case make these statistics configurable, so that self-hosted installations can disable (or adjust) the GA or Piwik integration.

**Comment by SeanJA** [comment]
it isn't used on pages with secret information though? https://github.com/onetimesecret/onetimesecret/search?utf8=%E2%9C%93&q=Secret+pages+are+not+tracked+in+any+way.

**Comment by rugk** [comment]
It is however used on the home page where users enter their note/secret information, so actually Google could read all this secret content with a modified JS.

**Comment by delano** [comment]
Good points all around. I'm planning a batch of work soon and I'll include something to address this.

**Comment by delano** [comment]
I've removed all traces of google analytics from the codebase. I left the `with_analytics` flag for folks that want to use a service for their own installations. The site is also now loading all js+css from local copies rather than a CDN. 

Thanks again for bringing this up. I'll close the ticket for now but feel free to open if you notice anything else.
