### ISSUE TITLE
Passphrase privacy settings are dismissed

### ISSUE THREAD

**Issue by pauliusbau** [onetimesecret/onetimesecret#525]
Hi. 
After a recent update, https://onetimesecret.com/ seems to dismiss a passphrase privacy setting. 
Even after setting passphrase, generate URL is freely accessible:
![paveikslas](https://github.com/user-attachments/assets/30c60525-fe0c-407b-8d7c-816b3aa374f0)
![paveikslas](https://github.com/user-attachments/assets/a32622c0-fa7b-48f5-80b6-15f26b095ace)
![paveikslas](https://github.com/user-attachments/assets/bcca4f9e-f1b0-4553-bb9b-893c60b78612)
![paveikslas](https://github.com/user-attachments/assets/930e0eb5-c378-4ced-8974-eaaed423b5f7)

**Comment by yjjqrqqq** [comment]
Also face this problem.

**Comment by marinejmartin** [comment]
I also experience this problem

**Comment by cristianjuarezz** [comment]
I've noticed this yesterday but didn't have the time to create an issue. It seems the passphrase data is not  being sent, however i've  remember seeing it in the payload yesterday and still didn't work.

![image](https://github.com/user-attachments/assets/5d00de8a-f64f-48d9-8deb-9ae20d7365d3)

**Comment by delano** [comment]
The fix is deployed. @cristianjuarezz That's exactly what it was: the name attribute was missing from the <input> field so the value wasn't being sent. 

<img width="743" alt="Screenshot 2024-08-01 at 07 03 39" src="https://github.com/user-attachments/assets/78a31f23-c12f-4b52-99aa-18570fd8ad27">

We weren't testing the case where a passphrase was entered but not sent. I'll work on a regression test so this doesn't happen again in the future. Thanks @pauliusbau for the quick report and @yjjqrqqq @marinejmartin for the confirmations.

**Comment by pauliusbau** [comment]
Thank you for a quick fix! 🍺
